#ifndef CONSTANTS_H
#define CONSTANTS_H

#define ENABLE_SERIAL 1

#define LED_BLINK_INTERVAL 500 // ms
#define UPDATE_RATE_MS 40

// Auger
#define AUGER_SPEED 15000000
#define AUGER_MID_POINT 1500
#define AUGER_DRILL_SPEED 50
#define AUGER_HOME_SPEED 10
#define AUGER_HOME_BACKOFF 100
#define AUGER_HOME_MAX_MILLIS 8000

#endif // CONSTANTS_H
