#ifndef CONSTANTS_H
#define CONSTANTS_H

#define ENABLE_SERIAL 1

#define LED_BLINK_INTERVAL 500 // ms
#define UPDATE_RATE_MS 40

// Auger
#define AUGER_SPEED 15000000
#define AUGER_DRILL_SPEED 50
#define AUGER_DRILL_IDLE_SIGNAL 1500

// Sample Slide
#define SS_OPEN_SAMPLE 25
#define SS_SAMPLE_CACHE 50
#define SS_MIDDLE_CONTAINER 75
#define SS_END_SAMPLE 100

#endif // CONSTANTS_H
